project:
  type: book
  execute-dir: project  # quarto should look to the project root (pendata)  
  output-dir: _webpage

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools: true    
    number-depth: 5
    toc-depth: 5
    toc-expand: true
    collapse-level: 1
    df-print: kable # tibble, kable, or paged

editor_options:
  chunk_output_type: console

editor:
  markdown:
    canonical: true  

execute:
  eval: true
  echo: true
  output: false
  freeze: auto  # auto: during global project renders, re-render only when source changes

book:
  title: "GNYHA preparation"
  author: "Don Boyd"
  date: today
  date-format: long
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - get_acs.qmd
    # - get_gnyha_data.qmd
    # - call_tc_cli.qmd

    # - part: "Extract Data"
    #   chapters:
    #     - get_and_save_extracted_data.qmd
    #     - test_extracted_data.qmd
    #     # extracted data stays in the work_data folder and does not need to be staged

# GROOT <- rprojroot::find_root(rprojroot::has_file(".git/index"))

# possible yaml at top of files qed

# ---
# editor_options: 
#   chunk_output_type: console
# editor:
#   markdown:
#     canonical: true  
# ---