# _quarto.yml
# _quarto.yml
project:
  type: manuscript
  execute-dir: project
  output-dir: _output

manuscript:
  article: report.qmd    

editor_options:
  chunk_output_type: console

format:
  typst:
    citeproc: false 
    toc: false  # We'll create custom TOC
    toc-title: Contents
    toc-depth: 3
    number-sections: true
    section-numbering: 1.1.a
    keep-typ: true
    papersize: us-letter
    margin:
      x: 1.25in
      y: 1.25in
    columns: 1  # Back to 1 as default
    fontsize: 9pt
    include-in-header: page-layout.typ
    logo:
      width: 3in
      location: center-bottom
      padding-bottom: 0.15in
