project:
  type: manuscript
  execute-dir: project  # quarto should look to the project root
  output-dir: _output

manuscript:
  article: report.qmd    

editor_options:
  chunk_output_type: console

execute:
  eval: true
  echo: true
  output: false
  freeze: false  # auto: during global project renders, re-render only when source changes
