---
project:
  type: default
  title: "GNYHA report"
  
format:
  typst:
    toc: true
    toc-depth: 4
    number-sections: true
    # number-depth: 4
    section-numbering: 1.1.a
    keep-typ: true
    papersize: us-letter
    margin:
      x: 1.25in
      y: 1.25in
    columns: 2
    output-dir: _report2
    fontsize: 12pt
    logo:
      width: 3in
      location: center-top
      padding-top: 0.25in
#    template: "templates/templates.typ"
---

<!-- format:
  typst:
    
    author: "Don Boyd"
    date: today
    date-format: long      
    toc: true
    section-numbering: 1.1.a
    columns: 2   -->

# Introduction

some text

## Now another section

Representative households should be consistent with wage and other data on hospital workers provided by the Greater New York Hospital Association, fleshed out to reflect the diversity of tax situations households are likely to face. For example, representative households should reflect, in realistic ways, different hospital occupations, family structures, regions of the state, home ownership or renting arrangements, spousal income levels, and other factors that influence, in important ways, how recent federal income tax changes will affect federal income taxes.

Representative households should be consistent with wage and other data on hospital workers provided by the Greater New York Hospital Association, fleshed out to reflect the diversity of tax situations households are likely to face. For example, representative households should reflect, in realistic ways, different hospital occupations, family structures, regions of the state, home ownership or renting arrangements, spousal income levels, and other factors that influence, in important ways, how recent federal income tax changes will affect federal income taxes.


Representative households should be consistent with wage and other data on hospital workers provided by the Greater New York Hospital Association, fleshed out to reflect the diversity of tax situations households are likely to face. For example, representative households should reflect, in realistic ways, different hospital occupations, family structures, regions of the state, home ownership or renting arrangements, spousal income levels, and other factors that influence, in important ways, how recent federal income tax changes will affect federal income taxes.

Representative households should be consistent with wage and other data on hospital workers provided by the Greater New York Hospital Association, fleshed out to reflect the diversity of tax situations households are likely to face. For example, representative households should reflect, in realistic ways, different hospital occupations, family structures, regions of the state, home ownership or renting arrangements, spousal income levels, and other factors that influence, in important ways, how recent federal income tax changes will affect federal income taxes.

Representative households should be consistent with wage and other data on hospital workers provided by the Greater New York Hospital Association, fleshed out to reflect the diversity of tax situations households are likely to face. For example, representative households should reflect, in realistic ways, different hospital occupations, family structures, regions of the state, home ownership or renting arrangements, spousal income levels, and other factors that influence, in important ways, how recent federal income tax changes will affect federal income taxes.

Representative households should be consistent with wage and other data on hospital workers provided by the Greater New York Hospital Association, fleshed out to reflect the diversity of tax situations households are likely to face. For example, representative households should reflect, in realistic ways, different hospital occupations, family structures, regions of the state, home ownership or renting arrangements, spousal income levels, and other factors that influence, in important ways, how recent federal income tax changes will affect federal income taxes.

Representative households should be consistent with wage and other data on hospital workers provided by the Greater New York Hospital Association, fleshed out to reflect the diversity of tax situations households are likely to face. For example, representative households should reflect, in realistic ways, different hospital occupations, family structures, regions of the state, home ownership or renting arrangements, spousal income levels, and other factors that influence, in important ways, how recent federal income tax changes will affect federal income taxes.


### Another subsection

#### Deeper subsection

then back up to level 2

## Level 2

Put a table here

```{=typst}
#table(
  columns: 4,
  table.header[Col 1][Col 2][Col 3][Col 4],
  [Row 1, Cell 1], [Row 1, Cell 2], [Row 1, Cell 3], [Row 1, Cell 4],
  [Row 2, Cell 1], [Row 2, Cell 2], [Row 2, Cell 3], [Row 2, Cell 4],
  // ... more rows of 4 cells
)

```

and another table here

```{=typst}
#let row2 = ([Row 2, Cell 1. This row uses a variable for each cell.],
             [Row 2, Cell 2. Edit as needed.],
             [Row 2, Cell 3. You can put paragraphs or sentences.],
             [Row 2, Cell 4. Variable example ends.])

#let cell_3_2 = [This is Row 3, Cell 2. Only this cell uses a variable.]

#table(
  columns: 4,
  table.header[Column 1][Column 2][Column 3][Column 4],
  [Row 1, Cell 1], [Row 1, Cell 2], [Row 1, Cell 3], [Row 1, Cell 4],
  ..row2,
  [Row 3, Cell 1], cell_3_2, [Row 3, Cell 3], [Row 3, Cell 4]
)

```
